# NumPy & Pandas — Data Wrangling Foundations
### A hands-on notebook covering vectorised computing and tabular data analysis


## Section 1 — NumPy 

NumPy (**Num**erical **Py**thon) is the backbone of scientific computing in Python.  
Almost every data library (Pandas, scikit-learn, TensorFlow…) builds on top of it.

### Why NumPy?
Python lists are flexible — they can hold any mix of data types. But that flexibility comes at a cost. When you do arithmetic on a list, Python processes each element one at a time, in a loop, checking the type of each item.

NumPy arrays store **one data type only**, which allows them to be stored as a contiguous block of memory. Operations run in compiled C code, not interpreted Python. The result is speed improvements of **10x to 100x** compared to equivalent Python loops.

For a dataset with 1 million numbers, the difference between a NumPy operation and a Python loop can be the difference between milliseconds and minutes.

Beyond speed, NumPy gives you:
- Multi-dimensional arrays (matrices, tensors)
- Broadcasting — operations between arrays of different shapes
- A complete library of mathematical and statistical functions
- The foundation that Pandas DataFrames are built on


In [3]:
import numpy as np
import time

# Python list loop — 1 million numbers
py_list = list(range(1_000_000))
start = time.perf_counter()
py_result = [x * 2 for x in py_list]
py_time = time.perf_counter() - start

# NumPy vectorised operation — same task
np_array = np.arange(1_000_000)
start = time.perf_counter()
np_result = np_array * 2
np_time = time.perf_counter() - start


print(f"Python list loop : {py_time*1000:.2f} ms")
print(f"NumPy vectorised : {np_time*1000:.2f} ms")
print(f"Speed-up         : {py_time/np_time:.1f}x")


Python list loop : 107.08 ms
NumPy vectorised : 2.31 ms
Speed-up         : 46.3x


### Creating Arrays

NumPy provides many ways to create arrays. The most common are:

**From existing data:**
- `np.array(list)` — convert a Python list to a NumPy array

**Generating arrays:**
- `np.zeros(shape)` — array filled with zeros
- `np.ones(shape)` — array filled with ones
- `np.full(shape, value)` — array filled with a specific value
- `np.arange(start, stop, step)` — like Python's `range()` but returns an array
- `np.linspace(start, stop, n)` — n evenly spaced values between start and stop
- `np.eye(n)` — identity matrix (n x n)
- `np.random.rand(shape)` — random floats between 0 and 1
- `np.random.randint(low, high, shape)` — random integers

In [14]:
# Create Array using different methods
array1 = np.array([1,2,3,4,5])
print("Array from list:", array1)

array2 = np.full((2,3), 5)
print("Array of zeros:\n", array2)

array3 = np.arange(1,20,2)
print("Array with range:", array3)

print(np.linspace(0,1,5))

print(np.eye(3))

Array from list: [1 2 3 4 5]
Array of zeros:
 [[5 5 5]
 [5 5 5]]
Array with range: [ 1  3  5  7  9 11 13 15 17 19]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:

random_array = np.random.rand(3,3)
print(random_array)

random_array2 = np.random.randint(0,10,(3,3))
print(random_array2)

random_array3 = np.random.seed(42)
print(np.random.rand(3,3))

[[0.63992102 0.14335329 0.94466892]
 [0.52184832 0.41466194 0.26455561]
 [0.77423369 0.45615033 0.56843395]]
[[0 4 5]
 [5 6 8]
 [4 1 4]]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


## Array Attributes

Every NumPy array has built-in attributes that tell you about its structure:

| Attribute | What it tells you | Example |
|-----------|------------------|---------|
| `.shape` | Dimensions as a tuple | `(3, 4)` = 3 rows, 4 cols |
| `.ndim` | Number of dimensions | `2` for a 2D array |
| `.size` | Total number of elements | `12` for a 3x4 array |
| `.dtype` | Data type of elements | `int64`, `float64` |

Understanding `dtype` is important — NumPy arrays are homogeneous (all same type). If you mix integers and floats, NumPy upcasts everything to float. If you mix numbers and strings, everything becomes a string.

In [27]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Shape of an array 
np.shape(arr_2d)

# Data Type of an Array
# print(np.dtype(arr_2d))

np.size(arr_2d)
print (arr_2d.dtype)
arr_2d.shape


int64


(2, 3)

### Vectorised Operations

Operations apply **element-wise** — no `for` loop needed.  
A scalar is automatically broadcast to match the array's shape.

One of the most important skills in NumPy is recognising when you can replace a Python loop with a vectorized operation. The result is the same but dramatically faster.

The key mindset shift: **think in terms of whole arrays, not individual elements.**

```python
# Slow — Python loop
result = []
for x in data:
    result.append(x * 2 + 1)

# Fast — vectorized
result = data * 2 + 1
```


In [29]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# Vectorized operations
arr_sum = a + b
print (arr_sum)

[11 22 33 44 55]


### Indexing and Slicing

NumPy indexing for 1D arrays works exactly like Python list indexing — zero-based, supports negative indexing.

For 2D arrays, you use two indices: `array[row, col]`. This is more efficient than Python's nested list syntax `array[row][col]`.

### Boolean Indexing

Pass a boolean array as an index → returns only the elements where the condition is `True`.  
This replaces the pattern `[x for x in arr if condition(x)]` with a single expression.


In [30]:
arr = np.array([10, 21, 31, 40, 51, 60, 70, 80])

# Access the first element
print (arr[0])


# Access the last element using negative indexing



# Access the element at index 4




10


### Slicing — Extracting Portions

Slicing works the same as Python lists: `array[start:stop:step]`. For 2D arrays, you slice rows and columns separately using a comma:

```python
array[row_start:row_stop, col_start:col_stop]
```

**Important — NumPy slices are views, not copies.** When you slice a NumPy array, you get a reference to the original data — not a new copy. If you modify the slice, you modify the original array. To get an independent copy, use `.copy()`.

This is a key difference from Python lists, where slices always return a copy.

In [34]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Get the first 4 elements
print (arr[0:4])

# Get elements from index 3 to 6


# Get every second element
print (arr[::2])


# Reverse the array using slicing
print (arr[::-1])


[10 20 30 40]
[10 30 50 70]
[80 70 60 50 40 30 20 10]


In [35]:
# Boolean Indexing

prices = np.array([150000, 320000, 280000, 450000, 195000, 510000])


# Inline — no need to name the mask
selected_prices = prices[prices > 300000]
print (selected_prices)


[320000 450000 510000]


### Statistical Functions

| Function | Returns |
|---|---|
| `np.mean(arr)` | Arithmetic mean |
| `np.sum(arr)` | Total |
| `np.min(arr)` / `np.max(arr)` | Smallest / largest |
| `np.std(arr)` | Standard deviation |
| `np.argmin(arr)` / `np.argmax(arr)` | **Index** of min / max |


In [37]:
prices = np.array([150000, 320000, 280000, 450000, 195000])

# Statistical Functions
print (np.mean(prices))


279000.0


### The `axis` Parameter

For 2D arrays the `axis` keyword controls the *direction* of the operation:

```
axis=0  →  operate DOWN the rows  →  one result per COLUMN
axis=1  →  operate ACROSS columns →  one result per ROW
```

A useful memory trick: `axis=0` **collapses rows** (the 0th dimension); `axis=1` **collapses columns**.


In [39]:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

print("No axis (grand total)  :", np.sum(data))
print("axis=0  (column sums)  :", np.sum(data, axis=0))   # [120 150 180]
print("axis=1  (row sums)     :", np.sum(data, axis=1))   # [ 60 150 240]

print("\nColumn means (axis=0)  :", np.mean(data, axis=0))
print("Row means    (axis=1)  :", np.mean(data, axis=1))


No axis (grand total)  : 450
axis=0  (column sums)  : [120 150 180]
axis=1  (row sums)     : [ 60 150 240]

Column means (axis=0)  : [40. 50. 60.]
Row means    (axis=1)  : [20. 50. 80.]


## Reshaping

Reshaping changes the dimensions of an array without changing its data. The total number of elements must remain the same.

| Method | What it does |
|--------|-------------|
| `.reshape(shape)` | Return array with new shape |
| `.flatten()` | Return a 1D copy of the array |
| `.ravel()` | Return a 1D view (no copy) |
| `.T` | Transpose — swap rows and columns |

You can use `-1` in reshape as a wildcard — NumPy calculates that dimension automatically. For example, `arr.reshape(2, -1)` means 2 rows, figure out the columns yourself.

In [49]:
flat = np.arange(12)                 # [0  1  2 … 11]
print("Original shape :", flat.shape)

# Reshape
dimension =flat.reshape(3,4)
print (dimension)
# Flatten
print("Flattened shape :", flat.flatten().shape)
print (flat.ravel())
# Transpose the matrix (swap rows and columns)
print (dimension.T)

Original shape : (12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened shape : (12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Numpy Exercise

Work with a raw 2D NumPy array — **no Pandas, no DataFrame**.

**The data (5 cars × 3 columns):**

| selling_price | km_driven | year |
|---|---|---|
| 450000 | 45000 | 2018 |
| 280000 | 80000 | 2015 |
| 620000 | 30000 | 2020 |
| 195000 | 120000 | 2012 |
| 340000 | 60000 | 2017 |

**Tasks:**
1. Compute average selling price and average km driven
2. Compute age of each car (`2024 − year`)
3. Find cars cheaper than ₹3,00,000 using boolean indexing
4. Find the index (and price) of the most expensive car using `np.argmax()`


In [56]:
print ("index and price of most expensive car:", np.argmax(cars[:,0]), cars[np.argmax(cars[:,0]),0])

index and price of most expensive car: 2 620000


In [51]:
# --- Data ---
cars = np.array([
    [450000, 45000, 2018],
    [280000, 80000, 2015],
    [620000, 30000, 2020],
    [195000, 120000, 2012],
    [340000, 60000, 2017],
])
print ("average selling price:", np.mean(cars[:,0]))
print ("average km driven :", np.mean(cars[:,1]))


average selling price: 377000.0
average km driven : 67000.0


In [54]:
print("cheaper cars :",cars[cars[:,0]<300000])

cheaper cars : [[280000  80000   2015]
 [195000 120000   2012]]


In [52]:
print ("age of cars:", 2024 -cars[:,2  ])

age of cars: [ 6  9  4 12  7]


## Section 2 — Pandas

NumPy gave us powerful numerical arrays. But real-world data is rarely just numbers in a grid — it has column names, row labels, mixed data types, and missing values. **Pandas** is built exactly for this kind of data.

Pandas is the most widely used data analysis library in Python. It is built on top of NumPy, so everything you learned about NumPy carries forward — Pandas adds a richer, labelled structure on top.

Pandas has two core data structures:

| Structure | What it is | Equivalent to |
|-----------|-----------|---------------|
| `Series` | 1-dimensional labelled array | A single column of data |
| `DataFrame` | 2-dimensional labelled table | A full spreadsheet or SQL table |



## Why Pandas?

With a Python list or NumPy array, data has no labels — you access it by position. If you have student data in an array, you have to remember that column 0 is name, column 1 is age, column 2 is GPA. This is fragile and confusing.

Pandas assigns **labels** to both rows and columns. You access data by name, not by position. This makes your code readable, your analysis clear, and your errors much easier to catch.

Beyond labels, Pandas gives you:
- Built-in handling of missing values
- Tools to load data from CSV, Excel, JSON, and databases
- Powerful grouping, filtering, and aggregation
- Integration with Matplotlib for visualisation
- The ability to work with datasets of millions of rows efficiently

By convention, Pandas is always imported as `pd`:

## Pandas Series

A **Series** is a one-dimensional array with an **index** — a label attached to each value. If you think of a dictionary, a Series is like a more powerful dictionary that supports arithmetic, statistics, and alignment.

```
Index    Value
  0   →   88
  1   →   76
  2   →   91
  3   →   55
```

The index does not have to be numbers — it can be strings (like student names), dates, or anything unique.

### Creating a Series

```python
pd.Series(data, index=index_labels)
```

You can create a Series from:
- A Python list
- A Python dictionary — keys become the index
- A NumPy array
- A single scalar value


### Series Attributes

| Attribute | What it returns |
|-----------|----------------|
| `.values` | The underlying NumPy array of values |
| `.index` | The index labels |
| `.dtype` | Data type of the values |
| `.shape` | Shape as a tuple |
| `.size` | Total number of elements |
| `.name` | Name of the Series |

In [4]:
import pandas as pd

# Create a Series from a list with default numeric index
pd.Series([10,20,30,40,50])


# Create a Series from a list with custom string index (student names)
pd.Series([85, 90, 78], index=['Alice', 'Bob', 'Charlie'])

# Create a Series from a dictionary — keys become the index automatically
pd.Series({'Alice': 85, 'Bob': 90, 'Charlie': 78})


# Print each Series and observe the output format


Alice      85
Bob        90
Charlie    78
dtype: int64

In [9]:
import pandas as pd

scores = pd.Series(
    [88, 76, 91, 55, 83],
    index=["Aarav", "Sita", "Bikash", "Nisha", "Rohan"],
    name="Exam Scores"
)

# Print: values, index, dtype, shape, size, name
scores.values
print(scores.index)
scores.dtype
scores.shape
scores.size


Index(['Aarav', 'Sita', 'Bikash', 'Nisha', 'Rohan'], dtype='str')


5

## Pandas DataFrame

A **DataFrame** is a 2-dimensional table with labelled rows and columns. Think of it as a collection of Series objects that all share the same index — each column is a Series.

This is the primary data structure you will use in all your data science work. Every dataset you load — CSV, Excel, JSON, database — becomes a DataFrame.

```
         name    age    course      gpa
0     Aarav     22     Data Sci    3.8
1      Sita     20     ML          3.6
2    Bikash     23     Data Sci    3.9
```

### Creating a DataFrame

The most common way is from a **dictionary of lists** — keys become column names, values become column data.

In [10]:
import pandas as pd

# Create a DataFrame from a dictionary of lists
# Columns: name, age, course, gpa, city
# At least 5 rows of student data

data = {
    "name"  : ["Aarav", "Sita", "Bikash", "Nisha", "Rohan"],
    "age"   : [22,20,23,21,22],
    "course": ["Data Science", "Machine Learning", "Python", "Machine Learning", "Data Science"],
    "gpa"   : [3.8, 3.6, 3.9, 3.4, 3.3],
    "city"  : ["Kathmandu", "Lalitpur", "Pokhara", "Butwal", "Bhairahawa"]
}




# Print the DataFrame
print(pd.DataFrame(data))

     name  age            course  gpa        city
0   Aarav   22      Data Science  3.8   Kathmandu
1    Sita   20  Machine Learning  3.6    Lalitpur
2  Bikash   23            Python  3.9     Pokhara
3   Nisha   21  Machine Learning  3.4      Butwal
4   Rohan   22      Data Science  3.3  Bhairahawa


In [19]:
import pandas as pd

df = pd.DataFrame({
    "name"   : ["Aarav", "Sita", "Bikash", "Nisha", "Rohan", "Hari", "Gita", "Priya"],
    "age"    : [22, 20, 23, 21, 22, 24, 20, 23],
    "course" : ["Data Science", "ML", "Data Science", "Python", "ML", "Data Science", "Python", "ML"],
    "gpa"    : [3.8, 3.6, 3.9, 3.4, 3.7, 3.5, 3.2, 3.8],
    "city"   : ["Kathmandu", "Lalitpur", "Pokhara", "Kathmandu", "Biratnagar", "Lalitpur", "Pokhara", "Kathmandu"]
})

# Print shape, columns, dtypes
print(df.shape)
print(df.columns)
print(df.dtypes)
# # Print first 3 rows using head()
print(df.head(3))


# # Print last 2 rows using tail()
print(df.tail(2))


# Print info() — observe dtypes and non-null counts
df.info()

# Print describe() — observe statistical summary
print(df.describe())

# Count how many students are in each course using value_counts()
print(df['course'].value_counts())


(8, 5)
Index(['name', 'age', 'course', 'gpa', 'city'], dtype='str')
name          str
age         int64
course        str
gpa       float64
city          str
dtype: object
     name  age        course  gpa       city
0   Aarav   22  Data Science  3.8  Kathmandu
1    Sita   20            ML  3.6   Lalitpur
2  Bikash   23  Data Science  3.9    Pokhara
    name  age  course  gpa       city
6   Gita   20  Python  3.2    Pokhara
7  Priya   23      ML  3.8  Kathmandu
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    8 non-null      str    
 1   age     8 non-null      int64  
 2   course  8 non-null      str    
 3   gpa     8 non-null      float64
 4   city    8 non-null      str    
dtypes: float64(1), int64(1), str(3)
memory usage: 452.0 bytes
             age      gpa
count   8.000000  8.00000
mean   21.875000  3.61250
std     1.457738  0.23566
min    20.000000  3

### Reading a CSV

`pd.read_csv('cars_details.csv')` parses the file and returns a DataFrame.  
The first row becomes column headers; Pandas assigns a 0-based integer index automatically.

> **Note for this notebook:** we create a sample DataFrame in-memory so no file is needed.  
> In your own work replace the cell below with `df = pd.read_csv('cars_details.csv')`.


In [ ]:
import pandas as pd

# ── Simulated dataset (mirrors cars_details.csv structure) ──────────────────
data = {
    'name'         : ['Maruti Swift', 'Honda City', 'Hyundai Creta',
                      'Toyota Innova', 'Ford EcoSport', 'Maruti Baleno',
                      'Tata Nexon', 'Volkswagen Polo', 'Kia Seltos', 'Renault Duster'],
    'year'         : [2018, 2016, 2020, 2015, 2017, 2019, 2021, 2014, 2022, 2016],
    'selling_price': [450000, 680000, 1050000, 920000, 520000,
                      390000, 780000, 280000, 1200000, None],
    'km_driven'    : [45000, 72000, 30000, 95000, 58000,
                      28000, 18000, 110000, 8000, 85000],
    'fuel'         : ['Petrol', 'Petrol', 'Diesel', 'Diesel', 'Petrol',
                      'Petrol', 'Petrol', 'Petrol', 'Petrol', 'Diesel'],
    'seller_type'  : ['Individual', 'Dealer', 'Dealer', 'Individual', 'Individual',
                      'Dealer', 'Dealer', 'Individual', 'Dealer', 'Individual'],
    'transmission' : ['Manual', 'Manual', 'Automatic', 'Manual', 'Manual',
                      'Manual', 'Automatic', 'Manual', 'Automatic', 'Manual'],
    'owner'        : ['First Owner', 'Second Owner', 'First Owner', 'Third Owner',
                      'First Owner', 'First Owner', 'First Owner',
                      'Fourth & Above Owner', 'First Owner', 'Second Owner'],
}



### First Inspection

Before analysing any dataset, always run these six commands in order:

| Method | What it tells you |
|---|---|
| `.shape` | `(rows, columns)` — size of the dataset |
| `.dtypes` | Data type of each column |
| `.head(n)` | First `n` rows (default 5) |
| `.tail(n)` | Last `n` rows |
| `.info()` | Column names, non-null counts, dtypes, memory |
| `.describe()` | Count, mean, std, min/max for numeric columns |


In [26]:
# Display the overall dimensions of the DataFrame (rows, columns)
df = pd.DataFrame(data)
print(df.shape)
# Show data types of each column to inspect schema consistency
print(df.dtypes)

# Preview the first 3 rows for quick initial inspection
print(df.head(3))

# Preview the last 2 rows to verify dataset ending and formatting
print(df.tail(2))

print(df.info())
print(df.describe())

(5, 5)
name          str
age         int64
course        str
gpa       float64
city          str
dtype: object
     name  age            course  gpa       city
0   Aarav   22      Data Science  3.8  Kathmandu
1    Sita   20  Machine Learning  3.6   Lalitpur
2  Bikash   23            Python  3.9    Pokhara
    name  age            course  gpa        city
3  Nisha   21  Machine Learning  3.4      Butwal
4  Rohan   22      Data Science  3.3  Bhairahawa
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    5 non-null      str    
 1   age     5 non-null      int64  
 2   course  5 non-null      str    
 3   gpa     5 non-null      float64
 4   city    5 non-null      str    
dtypes: float64(1), int64(1), str(3)
memory usage: 332.0 bytes
None
             age       gpa
count   5.000000  5.000000
mean   21.600000  3.600000
std     1.140175  0.254951
min    20.000000  3.30

In [27]:
# Display concise summary including column names, non-null counts, and data types
print(df.info())

# Generate statistical summary for numerical columns
print(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    5 non-null      str    
 1   age     5 non-null      int64  
 2   course  5 non-null      str    
 3   gpa     5 non-null      float64
 4   city    5 non-null      str    
dtypes: float64(1), int64(1), str(3)
memory usage: 332.0 bytes
None
             age       gpa
count   5.000000  5.000000
mean   21.600000  3.600000
std     1.140175  0.254951
min    20.000000  3.300000
25%    21.000000  3.400000
50%    22.000000  3.600000
75%    22.000000  3.800000
max    23.000000  3.900000


### Selecting Columns

`df['column']` → **Series** (single column)  
`df[['col1', 'col2']]` → **DataFrame** (multiple columns — note the double brackets)

This distinction matters: some operations only work on DataFrames, others only on Series.


In [33]:
# Single column → Series
print(df['course'])
# Multiple columns → DataFrame
# print(df)[['name', 'selling_price', 'km_driven']]

0        Data Science
1    Machine Learning
2              Python
3    Machine Learning
4        Data Science
Name: course, dtype: str


### Selecting Rows — `.loc[]` and `.iloc[]`

| | Selector | Use |
|---|---|---|
| `.loc[label]` | **Label-based** | Row label / column name |
| `.iloc[position]` | **Position-based** | Integer index (0, 1, 2 …) |

Both accept slices and lists.  
`.iloc` slicing is **exclusive** of the stop index (Python convention).  
`.loc` slicing is **inclusive** of the stop label.


In [ ]:
# First 3 rows by position
print(df.iloc[0:3])

# Specific rows by position
print(df.iloc[2])


     name  age            course  gpa       city
0   Aarav   22      Data Science  3.8  Kathmandu
1    Sita   20  Machine Learning  3.6   Lalitpur
2  Bikash   23            Python  3.9    Pokhara
name       Bikash
age            23
course     Python
gpa           3.9
city      Pokhara
Name: 2, dtype: object
Python


In [38]:

# loc — row label + column name
print(df.loc[2, 'course'])

# loc slice (inclusive on both ends)
print(df.loc[2:5, 'name':'gpa'])


Python
     name  age            course  gpa
2  Bikash   23            Python  3.9
3   Nisha   21  Machine Learning  3.4
4   Rohan   22      Data Science  3.3


### Filtering Rows (Boolean Indexing on DataFrames)

Same idea as NumPy boolean indexing — pass a condition that returns a boolean Series.

```python
df[df['selling_price'] > 300000]   # expensive cars
df[df['fuel'] == 'Diesel']         # diesel only
df[(condition1) & (condition2)]    # AND  — must wrap each in ()
df[(condition1) | (condition2)]    # OR
```

> Use `&` / `|` (bitwise), **not** `and` / `or` (Python keywords), when combining conditions.


In [ ]:
# Cars priced above 5 lakh
print(df[df['selling_price'] > 500000])

# Diesel cars only
print(df[df['fuel'] == 'Diesel'])

# Diesel AND manual transmission
print(df[(df['fuel'] == 'Diesel') & (df['transmission'] == 'Manual')])


KeyError: 'fuel'

### Missing Values

Real-world CSVs almost always have gaps.  
Pandas represents them as `NaN` (Not a Number).

| Method | Action |
|---|---|
| `df.isnull().sum()` | Count NaNs per column |
| `df.dropna()` | Remove **rows** with any NaN |
| `df.dropna(subset=['col'])` | Remove rows missing in a specific column |
| `df.fillna(value)` | Replace NaN with `value` |
| `df['col'].fillna(df['col'].median())` | Fill with column median |


In [45]:
# Check missing/null values in each column
df.isnull().sum()

# Fill missing values in 'selling_price' using the median value
# Median is preferred because it is less sensitive to outliers


# Confirm the replacement value used


# Verify that missing values have been handled


name      0
age       0
course    0
gpa       0
city      0
dtype: int64

### Adding New Columns

Assign the result of a vectorised expression to `df['new_column']`.  
This is exactly like NumPy — no loop, applied to the whole column at once.


In [46]:
# Age of each car
df['age'] = 2026 - df['year']
# Price efficiency — rupees per km


KeyError: 'year'

### `groupby` — Aggregating by Category

`df.groupby('column')` splits the DataFrame into groups.  
Chain an aggregation (`.mean()`, `.sum()`, `.max()`, `.count()`) to get one result per group.

```
df.groupby('fuel')['selling_price'].mean()
   ──────────────  ───────────────  ──────
   split by fuel   pick the column  aggregate
```


In [ ]:
# Average price by fuel type


# Highest price per seller type


# Average km driven by transmission


### Pandas Exercise

Use the DataFrame `df` already loaded above (or load from `cars_details.csv`).

**Tasks:**
1. Check for missing values — report which columns have nulls and how many
2. Handle missing values (drop or fill — justify your choice)
3. Add a `car_age` column (`2024 − year`)
4. Add a `price_per_km` column (`selling_price / km_driven`)
5. Filter: all **Diesel** cars with **Manual** transmission
6. Find average `selling_price` grouped by `fuel` type
7. Find the **most expensive car** for each `owner` type using `groupby` + `.max()`


In [ ]:
# Your Code Here


## Summary

| | NumPy | Pandas |
|---|---|---|
| **Best for** | Numerical computation, ML inputs | Tabular data, EDA, data cleaning |
| **Core object** | `ndarray` | `DataFrame` / `Series` |
| **Indexing** | Integer position | Label (`.loc`) or position (`.iloc`) |
| **Missing data** | No built-in support | `NaN`, `isnull()`, `fillna()` |
| **Grouping** | Manual with `np.where` | `groupby()` |

**Next steps:** Matplotlib / Seaborn for visualisation, then scikit-learn where both NumPy arrays and Pandas DataFrames become your model inputs.
